base_url = "https://hmemcpy.com"
title = "In Absentia"
description = "by Igal Tabachnik"
theme = "dinkleberg"

compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "categories"},
    {name = "tags"},
]

[markdown]
[markdown.highlighting]
enabled = true
theme = "nord"

[extra]
author = "Igal Tabachnik"
email = "hmemcpy@gmail.com"

blog_title = "In Absentia"

label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_relative_posts = "Related Posts"
label_next = "Next"
label_previous = "Previous"
label_page = "Page"
label_of = "of"

og_site_name = "In Absentia"
og_image = ""
og_alt_image = ""
keywords = "programming, software, scala, haskell, functional programming"

copyright_year = "2026"

twitter_username = "@hmemcpy"

sidebar = [
    {name = "Links", urls = [
        {name = "GitHub", url = "https://github.com/hmemcpy"},
        {name = "Twitter", url = "https://twitter.com/hmemcpy"},
    ]}
]
