base_url = "https://hmemcpy.com"
title = "In Absentia"
description = "by Igal Tabachnik"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml"]

# Configuration of the Markdown rendering
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown.highlighting]
enabled = true
theme = "nord"

[extra]
author = "Igal Tabachnik"
email = "hmemcpy@gmail.com"
github = "hmemcpy"
twitter = "hmemcpy"
disqus_shortname = "hmemcpy"

# Navigation
[[extra.nav]]
name = "Home"
url = "/"

[[extra.nav]]
name = "About"
url = "/about/"
