base_url = "https://hmemcpy.com"
title = "In Absentia"
description = "by Igal Tabachnik"
theme = "next-gemini"

compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "categories"},
    {name = "tags"},
]

[markdown]
[markdown.highlighting]
enabled = true
theme = "nord"

[extra]
author = "Igal Tabachnik"
email = "hmemcpy@gmail.com"
avatar = ""

og_site_name = "In Absentia"
keywords = "programming, software, scala, haskell, functional programming"
copyright_year = "2026"
twitter_username = "@hmemcpy"

menu = [
    {name = "Home",       url = "/"},
    {name = "Archives",   url = "/posts/"},
    {name = "Tags",       url = "/tags/"},
    {name = "Categories", url = "/categories/"},
    {name = "Talks",      url = "/talks-i-liked/"},
]

[extra.social]
GitHub  = "https://github.com/hmemcpy"
Twitter = "https://twitter.com/hmemcpy"
